name: Deploy To Azure Web App

on:
 push:
   branches: [ main ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Configure cert
        run: |
          mkdir .cert
          echo "$CERT_KEY" | base64 --decode > .cert/cert.key
          echo "$CERT_PEM" | base64 --decode > .cert/cert.pem
          echo "$REPO_ENV" | base64 --decode > ./web/admin/.env
          echo "$REPO_ENV" | base64 --decode > ./web/pangu-admin/.env
          echo "$REPO_ENV" | base64 --decode > ./web/pangu-home/.env
          echo "$REPO_ENV" | base64 --decode > ./web/mobile/.env
          echo "$PROD_ENV" | base64 --decode > .env
        env:
          CERT_KEY: ${{ secrets.CERT_KEY }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          PROD_ENV: ${{ secrets.PROD_ENV }}
          REPO_ENV: ${{ secrets.REPO_ENV }}
      - name: npm install, build
        run: |
          yarn install
          yarn build
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
