name: Deploy To Docker

on:
  push:
    tags:
      - '*'

jobs:
  deploy-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Configure cert
        run: |
          mkdir .cert
          echo "$CERT_KEY" | base64 --decode > .cert/cert.key
          echo "$CERT_PEM" | base64 --decode > .cert/cert.pem
          echo "$PROD_ENV" | base64 --decode > .env
        env:
          CERT_KEY: ${{ secrets.CERT_KEY }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          PROD_ENV: ${{ secrets.PROD_ENV }}

      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: upcwangying/flutter-boilerplate-store
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          tag_semver: true
