name: Deploy To Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Configure cert
        run: |
          mkdir .cert
          echo "$CERT_KEY" | base64 --decode > .cert/cert.key
          echo "$CERT_PEM" | base64 --decode > .cert/cert.pem
          echo "$REPO_ENV" | base64 --decode > ./web/admin/.env
          echo "$REPO_ENV" | base64 --decode > ./web/pangu-admin/.env
#          echo "$REPO_ENV" | base64 --decode > ./web/admin-react/.env
          echo "$REPO_ENV" | base64 --decode > ./web/pangu-home/.env
          echo "$REPO_ENV" | base64 --decode > ./web/mobile/.env
          echo "$PROD_ENV" | base64 --decode > .env
        env:
          CERT_KEY: ${{ secrets.CERT_KEY }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          PROD_ENV: ${{ secrets.PROD_ENV }}
          REPO_ENV: ${{ secrets.REPO_ENV }}

      - name: Remove git submodules
        run: rm -f .gitmodules

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_TS}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: ${{secrets.HEROKU_PROCFILE}}
          env_file: '.env'
