on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
name: Deploy to GitHub Pages
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Install deps
        run: pnpm i

#      - name: Configure env
#        run: |
#          echo "$DOCS_ENV" | base64 --decode > ./docs/.env
#        env:
#          DOCS_ENV: ${{ secrets.DOCS_ENV }}

      - name: Build
        run: pnpm build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/dist/
          cname: pangu.dev
          user_name: 'see'
          user_email: 'upcwangying@126.com'
