name: Deploy To Vercel

#on:
#  push:
#    branches: [ ssr-mpa ]

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure .env
        run: echo "$PROD_ENV" | base64 --decode > .env
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}

      - name: Deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
