on:
  push:
    tags:
      - 'desktop-*'
name: Release Desktop

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: npm

      - name: Install dependencies
        run: |
          yarn install
